### ISSUE TITLE
Forbidden error in doing an update on plan people

### ISSUE THREAD

**Issue by palidanx** [planningcenter/pco_api_ruby#11]
I'm trying to update a PlanPerson but get a Forbidden
```
api.services.v2.people[XXX].plan_people.patch(data: { type: 'PlanPerson', id: YYY, attributes: { status: 'C' } })
```
I get a
`PCO::API::Errors::Forbidden: Forbidden: You do not have access to this resource`

My account has full access as an OrganizationAdminsitrator.

With full access, should we be able to update this object?

**Comment by hayesr** [comment]
@palidanx You might want to ask this issue over on https://github.com/planningcenter/developers —it sounds like this might not be a problem with this library.

**Comment by seven1m** [comment]
@palidanx sorry we didn't notice this issue when you posted it back in June!

If you are still having trouble, definitely post an issue over at https://github.com/planningcenter/developers and someone can give you a hand.

Generally though, that error indicates your user doesn't have access to do the action. Make sure that the access token you are sending with the request is indeed that of the Org Admin...
