### ISSUE TITLE
Currently authenticated OAuth2 person

### ISSUE THREAD

**Issue by emersonian** [planningcenter/pco_api_ruby#2]
Is the undocumented https://api.planningcenteronline.com/people/v2/me endpoint safe to use in production, and should we expect it to stay there?

It would make a very useful addition to the OAuth2 summary at http://planningcenter.github.io/api-docs/#oauth-2.0

Perhaps I just missed it in the documentation, hunted around a bit before submitting and I do not see it.

**Comment by bensie** [comment]
Yes! `/people/v2/me` is definitely here to stay. In fact, it's just a shortcut to `/people/v2/people/:your_id`, where `:your_id` is the currently signed-in person. The payload returned is exactly the same.

**Comment by emersonian** [comment]
Great! Just making sure before pushing to production. Thanks!
