### ISSUE TITLE
Faraday 1.0ish

### ISSUE THREAD

**Issue by taylorbrooks** [planningcenter/pco_api_ruby#21]
Hey @seven1m!

Any chance the code in master could be cut into a new gem version?

I'm getting deprecation warnings on old Faraday code and it would be great to get the 1.8 version that is in master released.

**Comment by seven1m** [comment]
@taylorbrooks thanks for asking! This was pushed as version 2.0.1: https://rubygems.org/gems/pco_api/versions/2.0.1
