### ISSUE TITLE
Update `fee_cents` on Donation records

### ISSUE THREAD

**Issue by taylorbrooks** [planningcenter/pco_api_ruby#22]
According to API docs, the `fee_cents` attribute is "assignable". [0]

When I issue a PATCH request to add a value to `fee_cents`, I get the following 422 response:

`PCO::API::Errors::UnprocessableEntity (Validation Error: Donation fee must be less than or equal to 0)`

When calling the API like so:

```ruby
params = {
  data: {
    type: "Donation", 
      attributes: {
        payment_method: "ach", 
        received_at: "Tue, 09 Aug 2022 03:00:36.232620000 UTC +00:00", 
        fee_cents: 111
      }, 
      relationships: {
        payment_source: {
          data: { type: "PaymentSource", id: 13756 }
        }, 
        labels: {data: []}, 
        person: {
          data: { type: "Person", :id: 110522788 }
        }
      }
    }, 
  included: [
    {
      type: "Designation", 
      attributes: { amount_cents: 2250 }, 
      relationships: {
        fund: {
          data: { type: "Fund", id: 195545 }
        }
      }
    }
  ]
}

client.giving.v2.donations[pco_id].patch(params)
```

Is there anything obvious that I'm doing wrong here?

[0] https://developer.planning.center/docs/#/apps/giving/2019-10-18/vertices/donation

**Comment by seven1m** [comment]
Sorry, but this repo is just for the API client library. Can you copy your issue over to https://github.com/planningcenter/developers/issues ?

(I'm not sure what the answer is, but someone on our Giving team can help!)
