### ISSUE TITLE
Exception caused by 204 Response having blank body ("")

### ISSUE THREAD

**Issue by tpsands** [planningcenter/pco_api_ruby#24]
https://github.com/planningcenter/pco_api_ruby/blob/e82c4bbeb3b2723ecf83de80f8ed61b878a2aa9b/lib/pco/api/endpoint.rb#L87

I tried to post to assign_tags. The response is a 204 No Content. Potential fix could be:

```         
if result.body == ""
    res = Response[]
else
    res = Response[result.body]  
end
```

I ran the following code: `pcoCxn.services.v2.songs[newSongId].assign_tags.post(data: tagsToPost)`. I am certain the pcoCxn was set up properly and the tagsToPost object was correct because I debugged and saw the 204.

This was part of the error stack trace:

> /usr/local/lib/ruby/gems/3.1.0/gems/pco_api-2.0.1/lib/pco/api/endpoint.rb:87:in `[]': odd number of arguments for Hash (ArgumentError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/pco_api-2.0.1/lib/pco/api/endpoint.rb:87:in `_build_response'
        from /usr/local/lib/ruby/gems/3.1.0/gems/pco_api-2.0.1/lib/pco/api/endpoint.rb:57:in `post'

**Comment by tpsands** [comment]
Can we get this updated?

**Comment by seven1m** [comment]
Yeah, I'll work on a fix...
