### ISSUE TITLE
Faraday 2.0

### ISSUE THREAD

**Issue by taylorbrooks** [planningcenter/pco_api_ruby#26]
Hi there @seven1m!

In our application we are using various gems that reference Faraday > 2.x as a dependency.

`pco_api_ruby` relies on the `1.x` branch of Faraday.

I would be willing to open a PR that upgrades this gem to Faraday 2.x. My goal would be to keep the public interface the same and just change the internals. 

Would there be an appetite for merging it should that PR appear? :)

**Comment by seven1m** [comment]
@taylorbrooks yes, if you are willing to update the gem and make a PR, then that would be fine! We can review it and merge if nothing breaks. 😄

**Comment by taylorbrooks** [comment]
@seven1m Awesome. Thank you!

**Comment by taylorbrooks** [comment]
See #27

**Comment by seven1m** [comment]
@taylorbrooks thanks for working on this! I will check this out today and make sure it works with a couple of other internal projects of ours. Stand by!

**Comment by seven1m** [comment]
Sorry I didn't get to this yesterday. I will look at it today!
