### ISSUE TITLE
OAuth Updates

### ISSUE THREAD

**Issue by davidplappert** [planningcenter/pco_api_ruby#34]
1) Be able to use this gem to complete the oauth process and get access_token from a code

2) Auto-refresh access_token when expired using refresh token (and allow hook in setup config when refresh happens)

**Comment by seven1m** [comment]
@davidplappert have you seen our example repo here?

https://github.com/planningcenter/pco_api_oauth_example_sinatra_ruby

It does all that. This library is more of a low-level thing, so I don't think we'll be adding these things directly to the library. Let me know if the example repo helps!

**Comment by davidplappert** [comment]
> @davidplappert have you seen our example repo here?
> 
> https://github.com/planningcenter/pco_api_oauth_example_sinatra_ruby
> 
> It does all that. This library is more of a low-level thing, so I don't think we'll be adding these things directly to the library. Let me know if the example repo helps!

Yes, I saw it. I can understand keeping this separate. I have it working outside the gem. Thanks for the response.
