### ISSUE TITLE
POST Donations

### ISSUE THREAD

**Issue by taylorbrooks** [planningcenter/pco_api_ruby#4]
Tried a POST to `https://api.planningcenteronline.com/giving/v2/people/{{PEOPLE_ID}}/donations` and got "PCO::API::Errors::Forbidden: Forbidden: You do not have access to this resource".

Any plans to expose that functionality publicly?

**Comment by danott** [comment]
Howdy @taylorbrooks,

The Giving API is read-only for now. Exposing an endpoint to create donations is something that we have aspirations for, but there aren't any plans or timelines at this point.

Out of curiosity, what is your use case for wanting to create donations via the API? Knowing how people are going to use it can help us build the most useful API when it does become prioritized in the future!

**Comment by taylorbrooks** [comment]
Backstory: I run [SimpleDonation.com](https://simpledonation.com). 

There are a couple partner churches we work with that use Planning Center apps and want to use the Giving app -- either because they want to migrate away from us completely or because they just want to have that data in Planning Center.

Was trying to find a way to make transitioning data seamless.

From what I can tell, there isn't a way to batch import donations via CSV or anything. So I was looking to do it via the API.

**Comment by danott** [comment]
Apologies for the delay in reply. I lost this thread in a flurry of other GitHub notifications.

Thanks for the info about how you'd intend to use this part of the API. I don't have an expectation of when such an API would be available, so I'm going to close this thread for now.

Thanks!

**Comment by taylorbrooks** [comment]
Curious, if there's been any further discussion or thought on allowing donations to be created via the API.

**Comment by seven1m** [comment]
@taylorbrooks I'm sorry, we don't have any update on this at this time.
