### ISSUE TITLE
Faraday Warning

### ISSUE THREAD

**Issue by tylerbodway** [planningcenter/pco_api_ruby#5]
Every time I create an API instance, I'm met with this warning. I'm not sure if it's on your radar but I thought I'd post it just in case you're unaware.

```ruby
@api = PCO::API.new(basic_auth_token: "<TOKEN>", basic_auth_secret: "<SECRET>")

#=> WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
```

**Comment by bensie** [comment]
@tylerbodway Just cut v1.2.2 to fix this...thanks for reporting!
