### ISSUE TITLE
Email Question

### ISSUE THREAD

**Issue by tomrossi7** [planningcenter/pco_api_ruby#7]
We are looking to integrate with PCO People and your documentation and API looks great! One thing I'm worried about is everything we have is keyed off the email address, but I don't see that in the API. Is that not queryable?

**Comment by seven1m** [comment]
@tomrossi7 each person can have multiple email addresses. To access email addresses, you can query them like this:

```
api.people.v2.people[123].emails.get
```

Or, if you need to search for an email address:

```
api.people.v2.emails.get('where[address]' => 'tim@example.com')
```

For future questions about our API, please post them to https://github.com/planningcenter/developers/issues.

Thanks!

**Comment by tomrossi7** [comment]
Thanks @seven1m !
